export const catalogPublishers = {
  'aether-gazer': 'Yostar Games',
  'afk-journey': 'Farlight Games',
  'age-of-empires-mobile': 'Level Infinite',
  'arena-breakout': 'Level Infinite',
  'arena-of-valor': 'Garena',
  'asphalt-9': 'Gameloft',
  'astra-knights-of-veda': 'HYBE IM',
  'au2-mobile': 'UniPin',
  'banishers-faiths-entwined': 'Focus Entertainment',
  'battle-through-the-heavens-3d-fight': 'Yoozoo Games',
  'be-the-king': 'Tamatem Inc.',
  'bleach-soul-resonance': 'Nuverse',
  'blood-strike': 'NetEase Games',
  'blue-protocol-star-resonance': 'Bokura',
  'call-of-duty-mobile': 'Garena',
  'captain-tsubasa-ace': 'DeNA',
  'captain-tsubasa-dream-team': 'KLab',
  'castle-duels': 'MY.GAMES',
  chase: 'NetEase Games',
  crossfire: 'Smilegate',
  'crystal-of-atlan': 'Nuverse',
  'culinary-tour': 'Nacth Partner',
  'delta-force': 'Garena',
  'destiny-m': 'Nacth Partner',
  'destiny-rising': 'NetEase Games',
  'dragon-city': 'Socialpoint',
  'dragonheir-silent-gods': 'Nuverse',
  'draconia-saga': 'Sugarfun Game',
  'duet-night-abyss': 'Hero Entertainment',
  'eggy-party': 'NetEase Games',
  'farlight-84': 'Farlight Games',
  'fc-mobile': 'Electronic Arts',
  'football-master-2': 'GALA Sports',
  'frag-pro-shooter': 'Oh BiBi',
  'free-fire': 'Garena',
  'free-fire-max': 'Garena',
  'garena': 'Garena',
  'genshin-impact': 'HoYoverse',
  'ghost-story': 'NetEase Games',
  'growtopia': 'Ubisoft',
  'guns-of-glory': 'FunPlus',
  'haikyu-fly-high': 'Changyou',
  'harry-potter-magic-awakened': 'NetEase Games',
  'heaven-burns-red': 'Yostar Games',
  'heartopia': 'XD Entertainment',
  'heroic-uncle-kim': 'Nacth Partner',
  'heroes-evolved': 'NetDragon',
  'honkai-impact-3': 'HoYoverse',
  'honkai-star-rail': 'HoYoverse',
  'honor-of-kings': 'Level Infinite',
  'identity-v': 'NetEase Games',
  'indus-battle-royale-mobile': 'SuperGaming',
  'infinite-borders': 'NetEase Games',
  'isekai-feast': 'EYOUGAME',
  'kings-choice': 'ONEMT',
  'laplace-m': 'ZlongGames',
  'last-cloudia': 'AIDIS',
  'league-of-legends-pc': 'Riot Games',
  'league-of-legends-wild-rift': 'Riot Games',
  'legends-of-runeterra': 'Riot Games',
  'lifeafter-credits': 'NetEase Games',
  lineage2m: 'NCSOFT',
  'lordnine-infinite-class': 'Smilegate',
  'lords-mobile': 'IGG',
  'machina-waking': 'Nacth Partner',
  'magic-chess': 'Moonton',
  'marvel-rivals': 'NetEase Games',
  'melojam': 'PLAYPARK',
  'metal-slug-awakening': 'VNGGames',
  'mirren-star-legends': 'Nacth Partner',
  'mobile-legends': 'Moonton',
  'mobile-legends-adventure': 'Moonton',
  'modern-combat-5': 'Gameloft',
  'moonlight-blade-m': 'INFIPLAY',
  'mob-rush': 'Nacth Partner',
  'mu-origin-2': 'VNGGames',
  'mu-origin-3': 'FingerFun',
  'naruto-shippuden': 'Bandai Namco',
  'nba-infinite': 'Level Infinite',
  'octopath-traveler': 'Square Enix',
  'once-human': 'NetEase Games',
  'one-punch-man': 'FingerFun',
  'onmyoji-arena': 'NetEase Games',
  'overmortal': 'LTGAMES GLOBAL',
  'oxide-survival-island': 'Catsbit Games',
  'paw-tales-eternal-bond': 'Nacth Partner',
  'perfect-world-2': 'Perfect World Games',
  'persona-5-the-phantom-x': 'Perfect World Games',
  'pixel-gun-3d': 'Cubic Games',
  'point-blank': 'Zepetto',
  'pokemon-unite': 'The Pokemon Company',
  'pubg-mobile': 'Level Infinite',
  'pubg-mobile-lite': 'Level Infinite',
  'pubg-new-state-mobile': 'KRAFTON',
  'punishing-gray-raven': 'Kuro Games',
  'rainbow-six-mobile': 'Ubisoft',
  'ragnarok-idle-adventure-plus': 'Gravity Game Vision',
  'ragnarok-m-classic': 'Gravity Game Vision',
  'ragnarok-m-eternal-love': 'Gravity Game Link',
  'ragnarok-origin': 'Gravity Game Hub',
  'ragnarok-twilight': 'Gravity Game Vision',
  'razer-gold': 'Razer',
  'racing-master': 'NetEase Games',
  'revelation-infinite-journey': 'VNGGames',
  'rememento-white-shadow': 'Blackstorm',
  'sausage-man': 'XD Entertainment',
  'seal-m-sea': 'Playwith Games',
  'sega-football-club-champions': 'SEGA',
  'slime-haven': 'Nacth Partner',
  'smash-legends': '5minlab',
  'snowbreak-containment-zone': 'Seasun Games',
  'soul-land-new-world': 'Nacth Partner',
  'speed-drifters': 'Garena',
  'state-of-survival': 'FunPlus',
  'stumble-guys': 'Scopely',
  'super-sus': 'PIProductions',
  'sword-of-justice': 'NetEase Games',
  't3-arena': 'XD Entertainment',
  'tacticool': 'Panzerdog',
  'teamfight-tactics-mobile': 'Riot Games',
  'the-ants-underground-kingdom': 'StarUnion',
  'the-division-resurgence': 'Ubisoft',
  'the-moonlit-oath': 'Nacth Partner',
  'tom-and-jerry-chase': 'NetEase Games',
  'tomb-busters': 'Nacth Partner',
  'tower-of-fantasy': 'Level Infinite',
  'trails-of-cold-steel-nw': 'USERJOY',
  'undawn': 'Level Infinite',
  valorant: 'Riot Games',
  'war-robots': 'MY.GAMES',
  'watcher-of-realms': 'Moonton',
  'werewolf-party-game': 'Netease Games',
  'where-winds-meet': 'NetEase Games',
  'whiteout-survival-frost-star': 'Century Games',
  'world-war-heroes': 'Azur Interactive',
  'wuthering-waves': 'Kuro Games',
  'zenless-zone-zero': 'HoYoverse',
  zepeto: 'NAVER Z'
};

export const publisherForSlug = (slug) => catalogPublishers[slug] || 'Nacth Partner';
